### ISSUE TITLE
Positional encoding

### ISSUE THREAD

**Issue by dvirginz** [GiovanniTRA/transmatching#1]
Thank you very much for your paper!
Would you mind shedding some light on the positional encoding? I see you add a randomly initialized weight vector and not the Fourier signal as the original Perceiver. Would you please explain the design choice? Isn't that losing all the geometric information of the data?
Thanks!

**Comment by GiovanniTRA** [comment]
Hi Dvir,

Thank you for your interest in our paper :)
We used positional encodings exclusively for the latent probes, *not *for
the point clouds in input as to make the model permutation invariant wrt to
shuffling of the said point clouds.
We were not really interested in preserving geometric information ofthe
latent probes since they are randomly initialized parameters anyway, so we
used learnt positional encodings instead of the ones based on fourier.
If you do not care about the model being invariant to permutation, then you
can use the fourier positional encodings.

I hope I cleared your doubts, I am here if you need any further
clarification :)

Have a great evening, Gio

**Comment by dvirginz** [comment]
Thank you for the thorough answer,
Got it, thanks!
